name Run flyer script daily at 630 PM UTC

on
  schedule
    - cron 30 18     # Runs daily at 1830 UTC
  workflow_dispatch

jobs
  run-script
    runs-on ubuntu-latest

    steps
    - name Checkout repo
      uses actionscheckout@v3

    - name Set up Python
      uses actionssetup-python@v4
      with
        python-version '3.10'

    - name Install dependencies
      run pip install -r requirements.txt

    - name Run the flyer script
      run python flyers.py
