name: Run Python Script Every 5 Days

on:
  schedule:
    - cron: '0 0 */5 * *'   # Every 5 days at midnight UTC
  workflow_dispatch:        # Optional: lets you run it manually from GitHub

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # or your version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true

      - name: Run Script
        run: python flyers.py
