name: Run flyer script daily at 6:40 PM UTC

on:
  schedule:
    - cron: "40 18 * * *"  # Runs daily at 18:40 UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run the flyer script
      run: python flyers.py
